###############################################################################
# This file was automatically generated by extract_sage_libgap.py. DO NOT EDIT!
###############################################################################
#
#     Copyright (C) 2024 LaiTeP and contributors
#
#     This file is part of the sage_libgap distribution.
#     It is an automatically modified version of a file in the "Sage: a free
#     open-source mathematics software system" software package. Further
#     licensing information may be available further down this file.
#
#     The sage_libgap package is free software; you can redistribute it and/or
#     modify it under the terms of the GNU General Public License as published
#     by the Free Software Foundation, either version 3 of the License, or (at
#     your option) any later version.
#
#     The sage_libgap package is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
#     Public License for more details.
#
#     You should have received a copy of the GNU General Public License along
#     with sage_libgap package. If not, see <https://www.gnu.org/licenses/>.
#
###############################################################################

"""Common globals defined by GAP."""

###############################################################################
#       Copyright (C) 2009, William Stein <wstein@gmail.com>
#       Copyright (C) 2012, Volker Braun <vbraun.name@gmail.com>
#
#   Distributed under the terms of the GNU General Public License (GPL)
#   as published by the Free Software Foundation; either version 2 of
#   the License, or (at your option) any later version.
#                   http://www.gnu.org/licenses/
###############################################################################


from .gap_functions import common_gap_functions


# selected gap globals to use in tab completion
common_gap_globals = set([
  'Assert',
  'Cyclotomics',
  'GaussianIntegers',
  'GaussianRationals',
  'GlobalMersenneTwister',
  'GlobalRandomSource',
  'InfoAlgebra',
  'InfoAttributes',
  'InfoBckt',
  'InfoCharacterTable',
  'InfoCoh',
  'InfoComplement',
  'InfoCoset',
  'InfoFpGroup',
  'InfoGroebner',
  'InfoGroup',
  'InfoLattice',
  'InfoMatrix',
  'InfoMonomial',
  'InfoNumtheor',
  'InfoOptions',
  'InfoPackageLoading',
  'InfoPcSubgroup',
  'InfoWarning',
  'Integers',
  'NiceBasisFiltersInfo',
  'Primes',
  'Rationals',
  'TableOfMarksComponents'
]) | common_gap_functions
